" ------ 
" Author: Maria Ortiz
" Maintainers: Maria Ortiz
" Date: Jun 19, 2020
" License: 
" ------ 

" Vi Improved 
set nocompatible

" backspace 
set backspace=indent,eol,start 
set clipboard=unnamed
set laststatus=2
set noshowmode

" Plugins
call plug#begin(expand('~/.config/nvim/plugged'))

Plug 'itchyny/lightline.vim'
Plug 'ap/vim-buftabline' 
Plug 'luochen1990/rainbow'
Plug 'lifepillar/vim-solarized8'
Plug 'jiangmiao/auto-pairs'
call plug#end()

"Plugins setup
let g:rainbow_active = 1
syntax enable
set background=dark
colorscheme solarized8_high

" sets line numbers
set relativenumber number
highlight LineNr ctermfg=grey

" sets tabs to 4 spaces
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab

" sets parenthetical highlighting to just bold
hi MatchParen cterm=bold ctermbg=Black ctermfg=none

" sets noexpandtab for Makefiles
if &ft == 'make'
    setlocal noexpandtab
    setlocal tabstop=4
endif

" color columns beyond 80 characters
set colorcolumn=80
highlight ColorColumn ctermbg=red guibg=red

