" ------ 
" Author: Maria Ortiz
" Maintainers: Maria Ortiz
" Date: Jun 19, 2020
" License: 
" ------ 

" Vi Improved 
set nocompatible

" Plugins

" plug Config

" backspace 
set backspace=indent,eol,start 
set clipboard=unnamed

" sets up syntax highlighting
syntax enable

" sets line numbers
set relativenumber number
highlight LineNr ctermfg=grey

" sets tabs to 4 spaces
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab

" sets parenthetical highlighting to just bold
hi MatchParen cterm=bold ctermbg=Black ctermfg=none

" sets noexpandtab for Makefiles
if &ft == 'make'
    setlocal noexpandtab
    setlocal tabstop=4
endif

" color columns beyond 80 characters
set colorcolumn=80
highlight ColorColumn ctermbg=red guibg=red

" English spell check
set spelllang=en
set spell
